# -*- coding: utf-8 -*-
"""02_18241010_shababintisharrahman

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mogFA-pITA1m5RroagH4TmRdMzorRVki
"""

import pandas as pd
import numpy as np
from collections import Counter
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
income = pd.read_csv('/content/sample_data/Income Dataset (50k).csv')
income.head(3)

income.shape

income.isnull().sum()

income = income.dropna()
income.shape

income.isnull().sum()

income.info()

#income['workclass'].unique() #7
#income['occupation'].unique() #14
#income['race'].unique() #5
income['native-country'].unique() #7

income = income.drop(['education', 'relationship', 'capital-gain', 'capital-loss', 'native-country', ], axis = 1)
income.shape

income.info()

category_enc = pd.get_dummies(income['workclass'])
income['workclass'].head()

#category_enc2 = pd.get_dummies(income['occupation'])
#category_enc3 = pd.get_dummies(income['race'])
#category_enc4 = pd.get_dummies(income['gender'])

income.shape

y = pd.DataFrame(income['income_>50K'])
X_train, X_test, y_train, y_test = train_test_split(income['educational-num'], income['income_>50K'], test_size = 0.25, random_state=0, stratify = y)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)

income.info()