# -*- coding: utf-8 -*-
"""2_18241010_Shabab Intishar Rahman

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oH2uQlQQ0m_YLY_2zF0v-5txqKV_bpL9
"""

import random
 x = []
with open('input.txt') as f:
  lines= f.readlines()

for line in lines:
  x.append(line.split())

print (x)
fit = 0

for i in range(1, len(x)):
  if (x[i][0]) == 'l' :
   x[i][1] = -int(x[i][1])
  elif (x[i][0]) == 'd' :
     x[i][1] = int(x[i][1])
  i = i+1
#end of loop
population = []

for i in range (1, len(x)):
  population.append(x[i][1])
  i = i+1

print(population)
#creates a list of 0s the same length as the transactions for the day

sum = [0]*len(population)
output =[0]*len(population)
print (output)
print(len(population))

def function(sum,output,population):
  fit = 0
  for i in range(0,len(output)-1):
   if output[i] == 1:
     sum[i]=population[i]
     i=i+1
  for j in range(0,len(sum)-1):
    fit = fit + sum[j]
    j=j+1
#    print(fit)
  return fit
#above code block defines the fitness function

def algo(population,output) : 
  for a in range(0,20):
    while True:
      a = random.randint(0,len(population)-1)
#    if output[a] != 1 :
      output[a] = 1
      fitness = function(sum,output,population)
      if fitness == 0:
        print(output)
        break
      b = random.randint(0,len(population)-1)
#    if output[b] != 1:
      output[a] =0 #mutates the value of a variable to 0
      output[b] =1
      fitness = function(sum,output,population)    
      if fitness == 0:
        print(output)
        break
    a = a +1 
  print(-1)  
 
algo(population,output)



